alias ga='git add --all'
alias gac='git add --all && git commit -m'
alias gam='git commit --amend --reuse-message HEAD'
alias gb='git branch --verbose'
alias gbb='git branch'
alias gc='git commit --message'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gl='git log --abbrev-commit --graph --format=oneline'
alias gll='git log'
alias gp='git pull --ff-only'
alias gs='git status --short --branch'
alias gss='git status'